name: android
on:
  pull_request:
    paths:
      - "apps/android/**"
  push:
    branches: [main]
    paths:
      - "apps/android/**"

jobs:
  assemble:
    if: ${{ hashFiles('apps/android/gradlew') != '' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/android
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Assemble Debug
        run: ./gradlew :app:assembleDebug
