name: web
on:
  pull_request:
    paths: ["apps/web/**", ".github/workflows/web.yml"]
  push:
    branches: [main]
    paths: ["apps/web/**", ".github/workflows/web.yml"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
