name: web
on:
  pull_request:
    paths:
      - "apps/web/**"
  push:
    branches: [main]
    paths:
      - "apps/web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        run: |
          if [ -f ./package.json ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: ${{ steps.detect.outputs.present == 'true' }}
        with:
          node-version: 20

      - name: Install deps (ci if lockfile exists, else install)
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: |
          if [ -f ./package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        if: ${{ steps.detect.outputs.present == 'true' }}
        run: npm run build

      - name: Skip (Web project not present yet)
        if: ${{ steps.detect.outputs.present != 'true' }}
        run: echo "No package.json under apps/web; skipping build."
